---
title: "Tree Data Analysis"
author: "Tahmidul Islam"
date: "9/5/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, error=FALSE, message = FALSE, cache = TRUE, dpi = 300, fig.width = 14, fig.height = 6)
```



```{r}
library(dplyr)
library(ggplot2)
library(kableExtra)
library(tidyr)
```
# Tree Data

This dataset contains features of trees (height, width, etc.) from 3 sites: Brighton, Chase Stream and Lily Bay. There are 8 species in this sample.

Table: Data overview.
```{r}
tree <- read.csv("E:/R Project/BayesFDA/data/tree/tree.csv")
tree <- tree %>% dplyr::select(Site, ID.Code, Tree, Rep, Sp, Year, Height) %>% 
  filter(!is.na(Height)) %>% 
  mutate(id = paste0(Site, ID.Code, Rep), logHeight = log(Height))
head(tree) %>% kable()
```


Table: Distribution of site and species.
```{r}
sumDf <- tree %>% group_by(Site, Sp, id) %>% summarize (n = n()) %>% dplyr::select(Site, Sp)

sumDf %>% tally() %>% spread(Sp, n) %>% kable()
```

```{r}
ggplot(sumDf, aes(x = Site, fill = Sp)) + geom_bar(position="dodge", stat="count")
```

The measurements are collected few years apart: at 5, 10, 15, 16 and 27 years. 
```{r}
sumDf <- tree %>% group_by(Site, Year)  %>%  summarize(n = n())
sumDf %>% kable()
```

```{r}
ggplot(sumDf, aes(x = factor(Year), y = n, fill = Site)) + geom_col(position = 'dodge', stat = 'count')
```



```{r}
ggplot(data = tree, aes(x = Year, y = Height, col = Sp, group = id)) +
  geom_line(size = 1.5, alpha = .1) + facet_wrap(~Site)
```
```{r}
ggplot(data = tree, aes(x = Year, y = Height, col = Sp, group = id)) +
  geom_line(size = 1.5, alpha = .1)
```

